services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 2 --timeout 120
    volumes:
    - /var/www/nearestate-media:/app/media
    - /var/www/nearestate-static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    command: celery -A backend worker -l info
    volumes:
    - /var/www/nearestate-media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nearestate
      POSTGRES_USER: nearestate
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  postgres_data:

